export const COMMON_LANGUAGES = [
	{ code: "pt-BR", name: "Português (Brasil)" },
	{ code: "en-US", name: "English (United States)" },
	{ code: "es-ES", name: "Español (España)" },
	{ code: "fr-FR", name: "Français (France)" },
	{ code: "de-DE", name: "Deutsch (Deutschland)" },
	{ code: "it-IT", name: "Italiano (Italia)" },
	{ code: "pt-PT", name: "Português (Portugal)" },
	{ code: "en-GB", name: "English (United Kingdom)" },
	{ code: "ja-JP", name: "日本語 (日本)" },
	{ code: "zh-CN", name: "中文 (中国)" },
	{ code: "ko-KR", name: "한국어 (대한민국)" },
	{ code: "ru-RU", name: "Русский (Россия)" },
	{ code: "ar-SA", name: "العربية (المملكة العربية السعودية)" },
	{ code: "hi-IN", name: "हिन्दी (भारत)" },
	{ code: "nl-NL", name: "Nederlands (Nederland)" },
	{ code: "sv-SE", name: "Svenska (Sverige)" },
	{ code: "no-NO", name: "Norsk (Norge)" },
	{ code: "da-DK", name: "Dansk (Danmark)" },
	{ code: "fi-FI", name: "Suomi (Suomi)" },
	{ code: "pl-PL", name: "Polski (Polska)" },
	{ code: "tr-TR", name: "Türkçe (Türkiye)" },
	{ code: "el-GR", name: "Ελληνικά (Ελλάδα)" },
	{ code: "he-IL", name: "עברית (ישראל)" },
	{ code: "th-TH", name: "ไทย (ประเทศไทย)" },
	{ code: "vi-VN", name: "Tiếng Việt (Việt Nam)" },
];
